id: IE003A5FA
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:20:12.051329
last_modified: 2023-02-08 15:20:12.051468
source_metadata:
  title: 'PP: Ratnaguṇasaṃcayagāthā'
  language: sa
bases:
  04A1:
    base_file: 04A1.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
